import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createSeededSqliteD1 } from '../../slice-c/test/sqlite-d1.mjs';
import { previewTransactionManagement, executeTransactionManagementCommit } from '../src/transaction-management-protocol.mjs';
import { oneOffEligibility, buildOneOffPreview, buildOneOffReplacement } from '../src/one-off-payment-management.mjs';
import { runTerminalTransactionReadModel } from '../src/terminal-transaction-read-model.mjs';
import { runPortableBackup } from '../src/backup.mjs';
import { buildRestoreSql } from '../tools/portable-restore.mjs';
import { DatabaseSync } from 'node:sqlite';
import { SqliteD1Adapter } from '../../slice-c/test/sqlite-d1.mjs';

const migrations=['0006_new_functionality.sql','0007_reporting_cycles.sql','0008_other_income.sql','0009_typed_payment_effect.sql','0010_historical_one_offs.sql','0011_fixed_expenses.sql','0012_fixed_expense_weekly.sql','0013_transaction_identity.sql','0014_one_off_management_lifecycle.sql','0015_other_income_receipt_parent.sql','0016_obligation_payment_management.sql','0017_ktb_transfer_management.sql'];
function fixture(t){const value=createSeededSqliteD1();t.after(()=>value.raw.close());for(const name of migrations)value.raw.exec(fs.readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));value.raw.exec(`BEGIN;
INSERT INTO one_off_payments VALUES('p1','family','2026-09-10',NULL,'Original',10000,'Alex','2026-09-11T00:00:00.000Z','create-p1',NULL);
INSERT INTO one_off_payment_allocations VALUES('p1','Alex',10000);
INSERT INTO logical_transactions(logical_transaction_id,household_id,lifecycle_status,created_actor_email,created_at_utc,creation_request_id,creation_write_token,creation_committed_revision) VALUES('tx1','family','active','alex@example.com','2026-09-11T00:00:00.000Z','create-p1','create-write',1);
INSERT INTO logical_transaction_versions VALUES('v1','tx1',1,'one_off_payment','2026-09-10',1,'created',NULL);
INSERT INTO logical_transaction_components VALUES('v1','one_off_payment','p1','primary');
INSERT INTO logical_transaction_components VALUES('v1','one_off_payment_allocation','p1:Alex','allocation');
UPDATE logical_transactions SET terminal_version_id='v1' WHERE logical_transaction_id='tx1';
UPDATE household_revisions SET current_revision=1,last_write_token='create-write',updated_at='2026-09-11T00:00:00.000Z' WHERE household_id='family';COMMIT;`);return value;}
const opts=(extra={})=>({householdId:'family',actorEmail:'olga@example.com',nowIso:'2026-09-11T12:00:00.000Z',eligibility:oneOffEligibility,buildPreview:buildOneOffPreview,buildReplacement:buildOneOffReplacement,...extra});
const correction=(requestId='correct-1')=>({requestId,logicalTransactionId:'tx1',operation:'corrected',baseRevision:1,terminalVersionId:'v1',semanticPayload:{businessDate:'2026-09-09',description:'Corrected',categoryId:null,allocations:[{account:'Olga',amountSatang:12000}],reasonCode:'owner_correction'}});
const count=(raw,table)=>raw.prepare(`SELECT count(*) n FROM ${table}`).get().n;

test('one-off preview is zero-write and correction appends complete terminal facts with exact cash impact and replay',async t=>{const{db,raw}=fixture(t),before=raw.prepare('SELECT current_revision n FROM household_revisions').get().n;const request=correction();const preview=await previewTransactionManagement(db,{...request,correlationId:'one-off-preview'},'family',opts());assert.equal(preview.eligibility.eligible,true);assert.deepEqual(preview.impact.cashChangeSatang,{alexSatang:10000,olgaSatang:-12000});assert.equal(raw.prepare('SELECT current_revision n FROM household_revisions').get().n,before);const first=await executeTransactionManagementCommit(db,request,opts({writeToken:'write-correct'}));const replay=await executeTransactionManagementCommit(db,request,opts({writeToken:'unused'}));assert.deepEqual(replay,first);assert.equal(count(raw,'transaction_management_audit'),1);assert.equal(count(raw,'new_function_request_receipts'),1);const {model}=await runTerminalTransactionReadModel(db);const tx=model.activeTransactions.find(row=>row.logicalTransactionId==='tx1');assert.equal(tx.totalSatang,12000);assert.deepEqual(tx.allocations,[{account:'Olga',amountSatang:12000}]);assert.equal(tx.auditSummary.operationCount,1);assert.equal(count(raw,'one_off_payments'),7);});

test('delete, restore, and undo append versions and reconstruct the intended terminal lifecycle',async t=>{const{db,raw}=fixture(t);const del={requestId:'delete-1',logicalTransactionId:'tx1',operation:'deleted',baseRevision:1,terminalVersionId:'v1',semanticPayload:{reasonCode:'entered_by_mistake'}};const deleted=await executeTransactionManagementCommit(db,del,opts({writeToken:'write-delete'}));let model=(await runTerminalTransactionReadModel(db)).model;assert.ok(model.deletedTransactions.some(row=>row.logicalTransactionId==='tx1'));const restore={requestId:'restore-1',logicalTransactionId:'tx1',operation:'restored',baseRevision:2,terminalVersionId:deleted.terminalVersionId,semanticPayload:{reasonCode:'restore_last_active'}};const restored=await executeTransactionManagementCommit(db,restore,opts({writeToken:'write-restore',nowIso:'2026-09-11T12:01:00.000Z'}));model=(await runTerminalTransactionReadModel(db)).model;assert.ok(model.activeTransactions.some(row=>row.logicalTransactionId==='tx1'));const undo={requestId:'undo-1',logicalTransactionId:'tx1',operation:'undone',baseRevision:3,terminalVersionId:restored.terminalVersionId,semanticPayload:{reasonCode:'undo'}};await executeTransactionManagementCommit(db,undo,opts({writeToken:'write-undo',nowIso:'2026-09-11T12:02:00.000Z'}));model=(await runTerminalTransactionReadModel(db)).model;assert.ok(model.deletedTransactions.some(row=>row.logicalTransactionId==='tx1'));assert.equal(count(raw,'transaction_management_audit'),3);assert.equal(count(raw,'logical_transaction_versions'),4);});

test('invalid allocation, stale request, dependent undo, forced rollback, and other-family enablement fail closed',async t=>{const{db,raw}=fixture(t),before=count(raw,'financial_write_claims');await assert.rejects(executeTransactionManagementCommit(db,{...correction(),semanticPayload:{...correction().semanticPayload,allocations:[{account:'Alex',amountSatang:0}]}},opts()),error=>error.code==='INVALID_ALLOCATIONS');await assert.rejects(executeTransactionManagementCommit(db,{...correction(),baseRevision:0},opts()),error=>error.code==='STALE_MANAGEMENT_REVISION');await assert.rejects(executeTransactionManagementCommit(db,correction(),opts({writeToken:'fail-write',testOnlyForcedFailure:true})));assert.equal(count(raw,'financial_write_claims'),before);const del=await executeTransactionManagementCommit(db,{requestId:'delete-dep',logicalTransactionId:'tx1',operation:'deleted',baseRevision:1,terminalVersionId:'v1',semanticPayload:{reasonCode:'entered_by_mistake'}},opts({writeToken:'delete-dep-write'}));raw.prepare("UPDATE household_revisions SET current_revision=3 WHERE household_id='family'").run();const preview=await previewTransactionManagement(db,{logicalTransactionId:'tx1',operation:'undone',correlationId:'dep'},'family',opts({nowIso:'2026-09-11T12:01:00.000Z'}));assert.equal(preview.eligibility.eligible,false);assert.deepEqual(preview.eligibility.refusalCodes,['DEPENDENT_ACTIVITY_EXISTS']);assert.ok(del.terminalVersionId);});

test('portable restore preserves terminal meaning, eligibility, audit, replay, and the narrowed lifecycle trigger',async t=>{const{db}=fixture(t),request=correction('restore-proof'),committed=await executeTransactionManagementCommit(db,request,opts({writeToken:'restore-proof-write'}));const bucket={value:null,async put(key,value){this.value=value;},async list(){return{objects:[],truncated:false};},async delete(){}};await runPortableBackup(db,bucket,{environment:'test',createdAt:'2026-09-11T13:00:00.000Z',retentionDays:1});const restored=new DatabaseSync(':memory:');t.after(()=>restored.close());restored.exec('PRAGMA foreign_keys=ON');restored.exec(await buildRestoreSql(JSON.parse(bucket.value),{includeSchema:true}));const restoredDb=new SqliteD1Adapter(restored);assert.deepEqual(await executeTransactionManagementCommit(restoredDb,request,opts({writeToken:'unused'})),committed);assert.deepEqual((await runTerminalTransactionReadModel(restoredDb)).model,(await runTerminalTransactionReadModel(db)).model);const preview=await previewTransactionManagement(restoredDb,{logicalTransactionId:'tx1',operation:'deleted',correlationId:'restored'},'family',opts());assert.equal(preview.eligibility.eligible,true);assert.match(restored.prepare("SELECT sql FROM sqlite_master WHERE type='trigger' AND name='logical_transaction_terminal_lifecycle_matches'").get().sql,/['\"]undone['\"]/);});
