import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { createSeededSqliteD1, SqliteD1Adapter } from '../../slice-c/test/sqlite-d1.mjs';
import { executeOtherIncomeWrite, executeIncomeReceipt } from '../../slice-c/src/other-income.mjs';
import { previewTransactionManagement, executeTransactionManagementCommit } from '../src/transaction-management-protocol.mjs';
import { otherIncomeEligibility, buildOtherIncomePreview, buildOtherIncomeReplacement } from '../src/other-income-management.mjs';
import { runTerminalTransactionReadModel } from '../src/terminal-transaction-read-model.mjs';
import { runPortableBackup } from '../src/backup.mjs';
import { buildRestoreSql } from '../tools/portable-restore.mjs';
import { signSession } from '../src/auth.mjs';
import { handleFetch } from '../src/index.js';

const migrations=['0006_new_functionality.sql','0007_reporting_cycles.sql','0008_other_income.sql','0009_typed_payment_effect.sql','0010_historical_one_offs.sql','0011_fixed_expenses.sql','0012_fixed_expense_weekly.sql','0013_transaction_identity.sql','0014_one_off_management_lifecycle.sql','0015_other_income_receipt_parent.sql'];
const nowIso='2026-09-11T12:00:00.000Z';
const count=(raw,table)=>raw.prepare(`SELECT count(*) n FROM ${table}`).get().n;
function fixture(t){const value=createSeededSqliteD1();t.after(()=>value.raw.close());for(const name of migrations)value.raw.exec(fs.readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));return value;}
async function created(t){const value=fixture(t);const source=(await executeOtherIncomeWrite(value.db,{action:'addOtherIncomeSource',payload:{name:'Tutoring',requestId:'add-source'},nowIso,writeToken:'source-write'})).source;await executeOtherIncomeWrite(value.db,{action:'reactivateOtherIncomeSource',payload:{sourceId:source.other_income_source_id,effectiveDate:'2026-08-01',requestId:'past-source'},nowIso,writeToken:'past-source-write'});const receipt=await executeIncomeReceipt(value.db,{action:'incomeReceipt',actorEmail:'alex@example.com',nowIso,writeToken:'receipt-write',payload:{otherIncomeSourceId:source.other_income_source_id,requestId:'create-receipt',incomeAlexAmount:125,incomeOlgaAmount:75,date:'2026-09-10'}});return {...value,source,receipt};}
const opts=(extra={})=>({householdId:'family',actorEmail:'olga@example.com',nowIso,eligibility:otherIncomeEligibility,buildPreview:buildOtherIncomePreview,buildReplacement:buildOtherIncomeReplacement,...extra});
const correction=(sourceId,requestId='correct-income')=>({requestId,logicalTransactionId:'receipt-write:other-income-transaction',operation:'corrected',baseRevision:3,terminalVersionId:'receipt-write:other-income-version',semanticPayload:{businessDate:'2026-09-09',otherIncomeSourceId:sourceId,allocations:[{account:'Alex',amountSatang:5000},{account:'Olga',amountSatang:17500}],reasonCode:'owner_correction'}});

test('authorized migration is additive, immutable, and does not backfill historical receipts',t=>{const{raw}=fixture(t);assert.equal(count(raw,'other_income_receipt_parents'),0);assert.equal(count(raw,'other_income_receipt_allocations'),0);assert.ok(count(raw,'income_receipts')>0);raw.prepare("INSERT INTO other_income_receipt_parents VALUES('x','family',(SELECT other_income_source_id FROM other_income_sources LIMIT 1),'2026-09-10',1,'2026-09-11T00:00:00.000Z','x')").run();assert.throws(()=>raw.prepare("UPDATE other_income_receipt_parents SET total_satang=2 WHERE other_income_receipt_id='x'").run(),/immutable/);});

test('0015 preserves every pre-existing row byte-for-byte and creates no guessed parent',t=>{const value=createSeededSqliteD1();t.after(()=>value.raw.close());for(const name of migrations.slice(0,-1))value.raw.exec(fs.readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const names=value.raw.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(row=>row.name),before=Object.fromEntries(names.map(name=>[name,value.raw.prepare(`SELECT * FROM \"${name}\" ORDER BY rowid`).all()]));value.raw.exec(fs.readFileSync(new URL('../migrations/0015_other_income_receipt_parent.sql',import.meta.url),'utf8'));for(const name of names)assert.deepEqual(value.raw.prepare(`SELECT * FROM \"${name}\" ORDER BY rowid`).all(),before[name]);assert.equal(count(value.raw,'other_income_receipt_parents'),0);assert.equal(count(value.raw,'other_income_receipt_allocations'),0);assert.equal(value.raw.prepare('PRAGMA foreign_key_check').all().length,0);});

test('new split receipt creates one durable parent, exact allocations, identity, effects, and no salary transition',async t=>{const{db,raw,receipt}=await created(t);assert.equal(receipt.salaryCycleAdvanced,false);assert.equal(count(raw,'other_income_receipt_parents'),1);assert.equal(count(raw,'other_income_receipt_allocations'),2);const parent=raw.prepare('SELECT * FROM other_income_receipt_parents').get();assert.equal(parent.total_satang,20000);const model=(await runTerminalTransactionReadModel(db)).model;const tx=model.activeTransactions.find(row=>row.logicalTransactionId===receipt.logicalTransactionId);assert.equal(tx.kind,'other_income_receipt');assert.equal(tx.totalSatang,20000);assert.equal(tx.reconciliationState,'typed_effect_linked');assert.equal(tx.permittedActions.correct,true);});

test('preview is zero-write and correction atomically appends exact source, split receipts, cash effects, audit, and replay',async t=>{const{db,raw,source}=await created(t),before=raw.prepare('SELECT total_changes() n').get().n,request=correction(source.other_income_source_id);const preview=await previewTransactionManagement(db,{...request,correlationId:'income-preview'},'family',opts());assert.equal(preview.eligibility.eligible,true);assert.deepEqual(preview.impact.cashChangeSatang,{alexSatang:-7500,olgaSatang:10000});assert.equal(preview.impact.salaryCycleAdvanced,false);assert.equal(raw.prepare('SELECT total_changes() n').get().n,before);const first=await executeTransactionManagementCommit(db,request,opts({writeToken:'income-correct-write'}));assert.deepEqual(await executeTransactionManagementCommit(db,request,opts({writeToken:'unused'})),first);const tx=(await runTerminalTransactionReadModel(db)).model.activeTransactions.find(row=>row.logicalTransactionId===receiptId());assert.equal(tx.totalSatang,22500);assert.equal(tx.source,'Tutoring');assert.equal(tx.auditSummary.operationCount,1);assert.equal(count(raw,'transaction_management_audit'),1);});

test('correction removing one side still applies both account deltas in the final balance effect',async t=>{const{db,raw,source}=await created(t),latest=raw.prepare('SELECT alex_balance_satang,olga_balance_satang FROM balance_history ORDER BY business_date DESC,sheet_order DESC LIMIT 1').get(),request={...correction(source.other_income_source_id,'one-side'),semanticPayload:{businessDate:'2026-09-10',otherIncomeSourceId:source.other_income_source_id,allocations:[{account:'Olga',amountSatang:10000}],reasonCode:'owner_correction'}};await executeTransactionManagementCommit(db,request,opts({writeToken:'one-side-write'}));const after=raw.prepare('SELECT alex_balance_satang,olga_balance_satang FROM balance_history ORDER BY business_date DESC,sheet_order DESC LIMIT 1').get();assert.equal(after.alex_balance_satang,latest.alex_balance_satang-12500);assert.equal(after.olga_balance_satang,latest.olga_balance_satang+2500);});

test('delete, restore, and undo reconstruct lifecycle without changing salary state',async t=>{const{db,raw}=await created(t),salary=raw.prepare("SELECT * FROM salary_cycle_state WHERE household_id='family'").get();const del=await executeTransactionManagementCommit(db,{requestId:'delete-income',logicalTransactionId:receiptId(),operation:'deleted',baseRevision:3,terminalVersionId:'receipt-write:other-income-version',semanticPayload:{reasonCode:'entered_by_mistake'}},opts({writeToken:'delete-income-write'}));assert.ok((await runTerminalTransactionReadModel(db)).model.deletedTransactions.some(row=>row.logicalTransactionId===receiptId()));const restore=await executeTransactionManagementCommit(db,{requestId:'restore-income',logicalTransactionId:receiptId(),operation:'restored',baseRevision:4,terminalVersionId:del.terminalVersionId,semanticPayload:{reasonCode:'restore_last_active'}},opts({writeToken:'restore-income-write',nowIso:'2026-09-11T12:01:00.000Z'}));await executeTransactionManagementCommit(db,{requestId:'undo-income',logicalTransactionId:receiptId(),operation:'undone',baseRevision:5,terminalVersionId:restore.terminalVersionId,semanticPayload:{reasonCode:'undo'}},opts({writeToken:'undo-income-write',nowIso:'2026-09-11T12:02:00.000Z'}));assert.ok((await runTerminalTransactionReadModel(db)).model.deletedTransactions.some(row=>row.logicalTransactionId===receiptId()));assert.deepEqual(raw.prepare("SELECT * FROM salary_cycle_state WHERE household_id='family'").get(),salary);});

test('inactive source, stale state, replacement, and failed validation make no financial writes',async t=>{const{db,raw,source}=await created(t);const inactive=(await executeOtherIncomeWrite(db,{action:'addOtherIncomeSource',payload:{name:'Inactive choice',requestId:'inactive-source'},nowIso,writeToken:'inactive-write'})).source;const base=count(raw,'financial_write_claims');await assert.rejects(executeTransactionManagementCommit(db,{...correction(inactive.other_income_source_id),baseRevision:4},opts()),error=>error.code==='OTHER_INCOME_SOURCE_INACTIVE');await assert.rejects(executeTransactionManagementCommit(db,{...correction(source.other_income_source_id),baseRevision:2},opts()),error=>error.code==='STALE_MANAGEMENT_REVISION');await assert.rejects(executeTransactionManagementCommit(db,{...correction(source.other_income_source_id),operation:'replaced',baseRevision:4},opts()),error=>error.code==='REPLACEMENT_NOT_ENABLED');assert.equal(count(raw,'financial_write_claims'),base);});

test('invalid allocation, forced rollback, and dependent undo preserve every atomic boundary',async t=>{const{db,raw,source}=await created(t),before={claims:count(raw,'financial_write_claims'),parents:count(raw,'other_income_receipt_parents'),versions:count(raw,'logical_transaction_versions')};await assert.rejects(executeTransactionManagementCommit(db,{...correction(source.other_income_source_id),semanticPayload:{...correction(source.other_income_source_id).semanticPayload,allocations:[{account:'Alex',amountSatang:0}]}},opts()),error=>error.code==='INVALID_ALLOCATIONS');await assert.rejects(executeTransactionManagementCommit(db,correction(source.other_income_source_id,'forced-failure'),opts({writeToken:'forced-write',testOnlyForcedFailure:true})));assert.deepEqual({claims:count(raw,'financial_write_claims'),parents:count(raw,'other_income_receipt_parents'),versions:count(raw,'logical_transaction_versions')},before);const deleted=await executeTransactionManagementCommit(db,{requestId:'dependent-delete',logicalTransactionId:receiptId(),operation:'deleted',baseRevision:3,terminalVersionId:'receipt-write:other-income-version',semanticPayload:{reasonCode:'entered_by_mistake'}},opts({writeToken:'dependent-delete-write'}));raw.prepare("UPDATE household_revisions SET current_revision=5 WHERE household_id='family'").run();const preview=await previewTransactionManagement(db,{logicalTransactionId:receiptId(),operation:'undone',correlationId:'dependent-undo'},'family',opts({nowIso:'2026-09-11T12:01:00.000Z'}));assert.deepEqual(preview.eligibility.refusalCodes,['DEPENDENT_ACTIVITY_EXISTS']);assert.ok(deleted.terminalVersionId);});

test('portable restore preserves parent, allocations, terminal meaning, eligibility, audit, and exact replay',async t=>{const{db,source}=await created(t),request=correction(source.other_income_source_id,'restore-proof'),committed=await executeTransactionManagementCommit(db,request,opts({writeToken:'restore-proof-write'}));const bucket={value:null,async put(key,value){this.value=value;},async list(){return{objects:[],truncated:false};},async delete(){}};await runPortableBackup(db,bucket,{environment:'test',createdAt:'2026-09-11T13:00:00.000Z',retentionDays:1});const restored=new DatabaseSync(':memory:');t.after(()=>restored.close());restored.exec('PRAGMA foreign_keys=ON');restored.exec(await buildRestoreSql(JSON.parse(bucket.value),{includeSchema:true}));const restoredDb=new SqliteD1Adapter(restored);assert.deepEqual(await executeTransactionManagementCommit(restoredDb,request,opts({writeToken:'unused'})),committed);assert.deepEqual((await runTerminalTransactionReadModel(restoredDb)).model,(await runTerminalTransactionReadModel(db)).model);});

test('Worker exposes only authenticated same-origin other-income management and leaves salary disabled',async t=>{const{db,source}=await created(t),origin='https://family.example',env={DB:db,GOOGLE_CLIENT_ID:'client',APPROVED_GOOGLE_EMAILS:'approved@example.com',SESSION_SIGNING_KEY:'other-income-route-key-longer-than-thirty-two-bytes'};const token=await signSession({sub:'subject',email:'approved@example.com'},env,{jti:'other-income-route'});const request=(body,authenticated=true,requestOrigin=origin)=>new Request(`${origin}/api/action`,{method:'POST',headers:{origin:requestOrigin,...(authenticated?{cookie:`fcf_session=${token}`}:{ }),'content-type':'application/json'},body:JSON.stringify(body)});const payload={...correction(source.other_income_source_id),correlationId:'route-preview'};const preview=await handleFetch(request({apiAction:'transactionManagementPreview',payload}),env);assert.equal(preview.status,200);assert.equal((await preview.json()).eligibility.eligible,true);const commit=await handleFetch(request({apiAction:'transactionManagementCommit',payload:correction(source.other_income_source_id,'route-commit')}),env);assert.equal(commit.status,200);assert.equal((await commit.json()).operation,'corrected');assert.equal((await handleFetch(request({apiAction:'transactionManagementPreview',payload},false),env)).status,401);assert.equal((await handleFetch(request({apiAction:'transactionManagementPreview',payload},true,'https://evil.example'),env)).status,403);});

function receiptId(){return 'receipt-write:other-income-transaction';}
