import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { createSeededSqliteD1, SqliteD1Adapter } from '../../slice-c/test/sqlite-d1.mjs';
import { executeIncomeReceipt } from '../../slice-c/src/other-income.mjs';
import { runTerminalTransactionReadModel } from '../src/terminal-transaction-read-model.mjs';
import { previewTransactionManagement, executeTransactionManagementCommit } from '../src/transaction-management-protocol.mjs';
import { salaryReceiptEligibility, buildSalaryReceiptPreview, buildSalaryReceiptReplacement } from '../src/salary-receipt-management.mjs';
import { runPortableBackup } from '../src/backup.mjs';
import { buildRestoreSql } from '../tools/portable-restore.mjs';

const migrations=['0006_new_functionality.sql','0007_reporting_cycles.sql','0008_other_income.sql','0009_typed_payment_effect.sql','0010_historical_one_offs.sql','0011_fixed_expenses.sql','0012_fixed_expense_weekly.sql','0013_transaction_identity.sql','0014_one_off_management_lifecycle.sql','0015_other_income_receipt_parent.sql','0016_obligation_payment_management.sql','0017_ktb_transfer_management.sql','0018_fund_movement_management.sql','0019_salary_receipt_management.sql'];
function fixture(t,includeSalary=true){const f=createSeededSqliteD1();t.after(()=>f.raw.close());for(const name of migrations.slice(0,includeSalary?undefined:-1))f.raw.exec(fs.readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));return f;}
const options=value=>({householdId:'family',actorEmail:'olga@example.com',nowIso:'2026-08-14T12:05:00.000Z',eligibility:salaryReceiptEligibility,buildPreview:buildSalaryReceiptPreview,buildReplacement:buildSalaryReceiptReplacement,...value});
async function createSalary(t,alex=100,olga=0,{advance=false}={}){const f=fixture(t);if(!advance){f.raw.prepare('DELETE FROM salary_cycle_sources').run();f.raw.prepare("INSERT INTO salary_cycle_sources VALUES('family','2026-07-31','Olga Salary')").run();}const receipt=await executeIncomeReceipt(f.db,{householdId:'family',actorEmail:'alex@example.com',action:'incomeReceipt',writeToken:'salary-create',nowIso:'2026-08-14T12:00:00.000Z',payload:{requestId:'salary-create-request',incomeSource:'Alex Salary',incomeAlexAmount:alex,incomeOlgaAmount:olga,date:'2026-08-14'}});return{...f,receipt};}
async function transaction(db,id,life='active'){const model=(await runTerminalTransactionReadModel(db)).model;return(life==='active'?model.activeTransactions:model.deletedTransactions).find(row=>row.logicalTransactionId===id);}

test('0019 is additive, empty, immutable, and does not attach historical salary rows',t=>{const{raw}=fixture(t,false),before={receipts:raw.prepare('SELECT * FROM income_receipts ORDER BY receipt_id').all(),balances:raw.prepare('SELECT * FROM balance_history ORDER BY balance_row_id').all(),weeks:raw.prepare('SELECT * FROM weekly_snapshots ORDER BY week_start').all()};raw.exec(fs.readFileSync(new URL('../migrations/0019_salary_receipt_management.sql',import.meta.url),'utf8'));assert.equal(raw.prepare('SELECT count(*) n FROM salary_receipt_parents').get().n,0);assert.deepEqual(raw.prepare('SELECT * FROM income_receipts ORDER BY receipt_id').all(),before.receipts);assert.deepEqual(raw.prepare('SELECT * FROM balance_history ORDER BY balance_row_id').all(),before.balances);assert.deepEqual(raw.prepare('SELECT * FROM weekly_snapshots ORDER BY week_start').all(),before.weeks);});

test('Alex-only, Olga-only, and split salary creation produce one exact immutable typed identity',async t=>{for(const [alex,olga,count] of [[100,0,1],[0,125,1],[100,125,2]]){const{db,raw,receipt}=await createSalary(t,alex,olga),tx=await transaction(db,receipt.logicalTransactionId);assert.equal(tx.kind,'salary_receipt');assert.equal(tx.totalSatang,(alex+olga)*100);assert.equal(tx.allocations.length,count);assert.equal(tx.components.length,count*2);assert.equal(raw.prepare('SELECT count(*) n FROM salary_receipt_parents').get().n,1);assert.throws(()=>raw.prepare("UPDATE salary_receipt_parents SET source='x'").run(),/immutable/i);}});

test('salary correction, deletion, restore, undo, replay, stale, and replacement refusal are guarded',async t=>{const{db,raw,receipt}=await createSalary(t,100,100);let tx=await transaction(db,receipt.logicalTransactionId);const correction={requestId:'salary-correct',logicalTransactionId:tx.logicalTransactionId,operation:'corrected',baseRevision:1,terminalVersionId:tx.terminalVersion.id,semanticPayload:{businessDate:'2026-08-14',source:'Alex Salary',allocations:[{account:'Alex',amountSatang:15000},{account:'Olga',amountSatang:5000}],reasonCode:'owner_correction'}};const preview=await previewTransactionManagement(db,{...correction,correlationId:'salary-preview'},'family',options());assert.equal(preview.eligibility.eligible,true,JSON.stringify(preview.eligibility));assert.deepEqual(preview.impact.cashChangeSatang,{alexSatang:5000,olgaSatang:-5000});const answer=await executeTransactionManagementCommit(db,correction,options({writeToken:'salary-correct'}));assert.deepEqual(await executeTransactionManagementCommit(db,correction,options({writeToken:'unused'})),answer);tx=await transaction(db,tx.logicalTransactionId);assert.equal(tx.businessDate,'2026-08-14');await assert.rejects(executeTransactionManagementCommit(db,{...correction,requestId:'stale-salary'},options({writeToken:'stale'})),e=>e.code==='STALE_MANAGEMENT_REVISION');const replacement={...correction,requestId:'replace-salary',operation:'replaced',baseRevision:2,terminalVersionId:tx.terminalVersion.id};await assert.rejects(executeTransactionManagementCommit(db,replacement,options({writeToken:'replace'})),e=>e.code==='SALARY_REPLACEMENT_DISABLED');const del={requestId:'salary-delete',logicalTransactionId:tx.logicalTransactionId,operation:'deleted',baseRevision:2,terminalVersionId:tx.terminalVersion.id,semanticPayload:{reasonCode:'entered_by_mistake'}};await executeTransactionManagementCommit(db,del,options({writeToken:'salary-delete'}));tx=await transaction(db,tx.logicalTransactionId,'deleted');const restore={requestId:'salary-restore',logicalTransactionId:tx.logicalTransactionId,operation:'restored',baseRevision:3,terminalVersionId:tx.terminalVersion.id,semanticPayload:{reasonCode:'restore'}};await executeTransactionManagementCommit(db,restore,options({writeToken:'salary-restore'}));tx=await transaction(db,tx.logicalTransactionId);const undo={requestId:'salary-undo',logicalTransactionId:tx.logicalTransactionId,operation:'undone',baseRevision:4,terminalVersionId:tx.terminalVersion.id,semanticPayload:{reasonCode:'undo'}};await executeTransactionManagementCommit(db,undo,options({writeToken:'salary-undo',nowIso:'2026-08-14T12:06:00.000Z'}));assert.equal((await transaction(db,tx.logicalTransactionId,'deleted')).lifecycle,'deleted');assert.equal(raw.prepare('SELECT count(*) n FROM transaction_management_audit').get().n,4);});

test('opening-cycle mutation conflicts preserve reporting boundaries, weeks, observations, and next salary null',async t=>{const{db,raw,receipt}=await createSalary(t,100,0,{advance:true}),tx=await transaction(db,receipt.logicalTransactionId),before={weeks:raw.prepare('SELECT * FROM weekly_snapshots ORDER BY week_start').all(),balances:raw.prepare("SELECT * FROM balance_history WHERE source_sheet<>'Cloudflare' ORDER BY balance_row_id").all(),boundaries:raw.prepare('SELECT * FROM reporting_salary_cycles ORDER BY cycle_start').all()};assert.equal(raw.prepare('SELECT next_salary_date n FROM salary_cycle_state').get().n,null);const del={requestId:'delete-opening',logicalTransactionId:tx.logicalTransactionId,operation:'deleted',baseRevision:1,terminalVersionId:tx.terminalVersion.id,semanticPayload:{reasonCode:'entered_by_mistake'}};const refused=await previewTransactionManagement(db,{...del,correlationId:'p'},'family',options());assert.equal(refused.eligibility.eligible,false);assert.deepEqual(refused.eligibility.refusalCodes,['PRESERVED_REPORTING_BOUNDARY_CONFLICT']);assert.deepEqual(raw.prepare('SELECT * FROM weekly_snapshots ORDER BY week_start').all(),before.weeks);assert.deepEqual(raw.prepare("SELECT * FROM balance_history WHERE source_sheet<>'Cloudflare' ORDER BY balance_row_id").all(),before.balances);assert.deepEqual(raw.prepare('SELECT * FROM reporting_salary_cycles ORDER BY cycle_start').all(),before.boundaries);});

test('forced failure rolls back every salary fact and portable restore preserves canonical eligibility and replay',async t=>{const{db,raw,receipt}=await createSalary(t),tx=await transaction(db,receipt.logicalTransactionId),request={requestId:'salary-fail',logicalTransactionId:tx.logicalTransactionId,operation:'corrected',baseRevision:1,terminalVersionId:tx.terminalVersion.id,semanticPayload:{businessDate:'2026-08-14',source:'Alex Salary',allocations:[{account:'Alex',amountSatang:9000}],reasonCode:'owner_correction'}},count=raw.prepare('SELECT count(*) n FROM salary_receipt_parents').get().n;await assert.rejects(executeTransactionManagementCommit(db,request,options({writeToken:'salary-fail',testOnlyForcedFailure:true})));assert.equal(raw.prepare('SELECT count(*) n FROM salary_receipt_parents').get().n,count);const good={...request,requestId:'salary-good'};await executeTransactionManagementCommit(db,good,options({writeToken:'salary-good'}));const bucket={value:null,async put(k,v){this.value=v},async list(){return{objects:[],truncated:false}},async delete(){}};await runPortableBackup(db,bucket,{environment:'test',createdAt:'2026-08-14T13:00:00.000Z',retentionDays:1});const restored=new DatabaseSync(':memory:');t.after(()=>restored.close());restored.exec('PRAGMA foreign_keys=ON');restored.exec(await buildRestoreSql(JSON.parse(bucket.value),{includeSchema:true}));const restoredDb=new SqliteD1Adapter(restored);assert.deepEqual((await runTerminalTransactionReadModel(restoredDb)).model,(await runTerminalTransactionReadModel(db)).model);assert.equal(restored.prepare('PRAGMA foreign_key_check').all().length,0);assert.deepEqual(await executeTransactionManagementCommit(restoredDb,good,options({writeToken:'unused'})),await executeTransactionManagementCommit(db,good,options({writeToken:'unused'})));});

test('invalid actor, unsafe amount, variable source, partial schema, and ambiguous legacy salary fail closed',async t=>{const{db,raw}=fixture(t);await assert.rejects(executeIncomeReceipt(db,{action:'incomeReceipt',actorEmail:'',nowIso:'2026-08-14T12:00:00.000Z',payload:{requestId:'no-actor',incomeSource:'Alex Salary',incomeAlexAmount:1,date:'2026-08-14'}}),/actor/i);await assert.rejects(executeIncomeReceipt(db,{action:'incomeReceipt',actorEmail:'a@b',nowIso:'2026-08-14T12:00:00.000Z',payload:{requestId:'bad-amount',incomeSource:'Alex Salary',incomeAlexAmount:Number.MAX_SAFE_INTEGER,date:'2026-08-14'}}));assert.equal(raw.prepare("SELECT count(*) n FROM logical_transaction_versions WHERE kind='salary_receipt'").get().n,0);raw.prepare('DROP TRIGGER salary_receipt_parent_delete_forbidden').run();const bucket={async put(){},async list(){return{objects:[]}},async delete(){}};await assert.rejects(runPortableBackup(db,bucket,{environment:'test'}),/schema|unsupported/i);});
