const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const calendar=require('../../../assets/v24/v24_1_obligation_calendar.js');
const root=path.resolve(__dirname,'../../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'assets/v24/v24_1_obligation_calendar.css'),'utf8');
test('Current guidance precedes all three pace summaries and uses gold treatment',()=>{const panel=html.match(/data-tab-panel="pace"[\s\S]*?<\/section>/)[0];assert.ok(panel.indexOf('pace-guidance-gold')<panel.indexOf('pace-summary'));assert.match(css,/background:#f5c84c/)});
test('calendar uses Bangkok month, includes boundaries, and orders date then name',()=>{const items=[{name:'Zulu',dueDate:'2026-09-30',status:'Outstanding',remainingAmount:1},{name:'Beta',dueDate:'2026-09-01',status:'Due today',remainingAmount:2},{name:'Alpha',dueDate:'2026-09-01',status:'Partially paid',remainingAmount:1},{name:'Other month',dueDate:'2026-10-01',status:'Outstanding',remainingAmount:1}];const c=calendar.build(items,'2026-09-07');assert.equal(c.month,'2026-09');assert.deepEqual(c.cells.filter(Boolean).flatMap(x=>x.items).map(x=>x.name),['Alpha','Beta','Zulu']);assert.equal(c.cells.filter(Boolean).length,30)});
test('statuses collapse to the required labels',()=>{assert.equal(calendar.normalizedStatus({status:'Paid',remainingAmount:0}),'Paid');assert.equal(calendar.normalizedStatus({status:'Partially paid',remainingAmount:4}),'Outstanding');assert.equal(calendar.normalizedStatus({status:'Due today',remainingAmount:4}),'Outstanding');assert.equal(calendar.normalizedStatus({status:'Overdue',remainingAmount:4}),'Overdue')});
test('multiple same-day obligations remain together and empty dates remain represented',()=>{const c=calendar.build([{name:'A',dueDate:'2026-09-08',remainingAmount:1},{name:'B',dueDate:'2026-09-08',remainingAmount:1}],'2026-09-07');assert.equal(c.cells.find(x=>x&&x.day===8).items.length,2);assert.equal(c.cells.find(x=>x&&x.day===9).items.length,0)});
test('mobile calendar prevents clipping and horizontal layout',()=>{assert.match(css,/@media\(max-width:760px\)[\s\S]*\.obligation-calendar\{grid-template-columns:1fr\}/);assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/\.calendar-day\.empty\{display:none\}/)});
test('management and payment access remain present',()=>{assert.match(html,/v24_1_fixed\.js/);const app=fs.readFileSync(path.join(root,'assets/v24/v24_1_app1.js'),'utf8');assert.match(app,/obligation-payment-btn/)});
